<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XufusLite.Core\XufusLite.Core.csproj" />
    <ProjectReference Include="..\XufusLite.Infrastructure\XufusLite.Infrastructure.csproj" />
  </ItemGroup>
</Project>
